from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # Salesforce (auth via SF CLI stored OAuth token)
    sf_username: str = ""
    sf_live: bool = False

    # Nutanix Insights Portal (headless browser auth via persistent Chromium profile)
    nutanix_insights_api_url: str = "https://portal.example.com/api/v1"
    nutanix_insights_api_key: str = ""
    insights_cookie_auth: bool = True  # kept for backwards compat; ignored
    insights_live: bool = False

    # CS Insights Portal (headless browser auth via persistent Chromium profile)
    csinsights_base_url: str = "https://csinsights.internal.example"
    csinsights_api_key: str = ""
    csinsights_api_secret: str = ""
    csinsights_cookie_auth: bool = True  # kept for backwards compat; ignored
    csinsights_live: bool = False

    # Planhat (headless browser auth via persistent Chromium profile —
    # cookie-bound, no API keys, no stored credentials).
    #
    # ``planhat_base_url`` is the SPA workspace URL the bridge navigates
    # to in order to attach to the authenticated session — this is what
    # appears in the address bar after sign-in (e.g. for the Nutanix
    # tenant: ``https://app.planhat.example/your-tenant``).
    #
    # ``planhat_api_base_url`` is the host root the SPA hits for cookie-
    # authenticated XHRs (e.g. ``https://app.planhat.example/api``). When
    # blank it is auto-derived from ``planhat_base_url`` — scheme://host
    # plus ``/api`` — which matches the standard Planhat layout. Override
    # only if your tenant serves the API under an unusual prefix, which
    # ``scripts/planhat_login.py`` will surface in
    # ``.browser_state/planhat_api_calls.json``.
    planhat_base_url: str = "https://app.planhat.example/your-tenant"
    planhat_api_base_url: str = ""  # blank = auto-derive from planhat_base_url
    planhat_cookie_auth: bool = True  # kept for symmetry; ignored
    planhat_live: bool = False

    # Microsoft Graph API (Outlook email integration — legacy, blocked by Conditional Access)
    ms_graph_client_id: str = ""
    ms_graph_client_secret: str = ""
    ms_graph_tenant_id: str = ""
    ms_graph_redirect_uri: str = "http://localhost:8000/auth/callback"
    ms_graph_scopes: str = "Mail.Send Mail.ReadWrite User.Read"

    # macOS Outlook app (recommended — zero setup, uses local Outlook via AppleScript)
    outlook_send_via_app: bool = True

    # Power Automate webhook (alternative — bypasses Conditional Access)
    power_automate_webhook_url: str = ""
    power_automate_sender_email: str = ""

    # Email defaults
    email_sender_name: str = "Technical Account Management"
    email_signature: str = (
        "Best regards,\n"
        "Technical Account Management Team\n"
        "This is an automated risk assessment generated by the Adoption & Escalation Risk Analyzer (demo)."
    )

    # Internal engagement (uses existing SF connection — no extra config)
    engagement_live: bool = True  # auto-enabled when SF is live

    # Application — this public build ships in demo mode (synthetic data only).
    demo_mode: bool = True
    refresh_interval_minutes: int = 30
    risk_threshold_high: int = 75
    risk_threshold_medium: int = 50
    log_level: str = "INFO"

    # Background sync (per-source ingestion workers — see app/sync/)
    sync_db_path: str = "data/app.db"
    sync_interval_hours: int = 24
    sync_enabled: bool = True
    sync_account_concurrency: int = 5  # parallel per-account fetches per worker
    sync_max_accounts_per_run: int = 0  # 0 = no limit; useful for staging/dev
    sync_stale_after_hours: int = 30  # UI staleness threshold (24h cycle + 6h buffer)

    # AI self-heal (Ollama-backed; failure-only invocation)
    ai_heal_enabled: bool = True
    ai_heal_max_retries: int = 3
    ollama_base_url: str = "http://localhost:11434"
    ollama_model: str = "gemma4:latest"

    # Event bus (optional — fan snapshots out to Memphis / NATS in
    # addition to the always-on direct fan-out into SQLite + ChromaDB).
    event_bus_enabled: bool = False
    event_bus_backend: str = "null"   # 'null' | 'memphis' | 'nats'
    event_bus_subject_prefix: str = "snapshots"
    memphis_host: str = "localhost"
    memphis_port: int = 6666
    memphis_username: str = ""
    memphis_password: str = ""
    memphis_account_id: int = 1
    nats_url: str = "nats://localhost:4222"

    # ``extra="ignore"`` lets the same .env carry vars consumed by other
    # libs (HF_HUB_OFFLINE, TRANSFORMERS_OFFLINE, …) without pydantic
    # erroring out on undeclared keys.
    model_config = {
        "env_file": ".env",
        "env_file_encoding": "utf-8",
        "extra": "ignore",
    }


settings = Settings()
